export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpeg",
    username: "Safak Kocaoglu",
    status: "active",
  },
  {
    id: 2,
    profilePicture: "person/2.jpeg",
    username: "Janell Shrum",
    status: "active",
  },
  {
    id: 3,
    profilePicture: "person/3.jpeg",
    username: "Alex Durden",
    status: "active",
  },
  {
    id: 4,
    profilePicture: "person/4.jpeg",
    username: "Dora Hawks",
    status: "active",
  },
  {
    id: 5,
    profilePicture: "person/5.jpeg",
    username: "Thomas Holden",
    status: "active",
  },
  {
    id: 6,
    profilePicture: "person/6.jpeg",
    username: "Shirley Beauchamp",
    status: "active",
  },
  {
    id: 7,
    profilePicture: "person/7.jpeg",
    username: "Travis Bennett",
    status: "active",
  },
  {
    id: 8,
    profilePicture: "person/8.jpeg",
    username: "Kristen Thomas",
    status: "active",
  },
  {
    id: 9,
    profilePicture: "person/9.jpeg",
    username: "Gary Duty",
    status: "active",
  },
  {
    id: 10,
    profilePicture: "person/10.jpeg",
    username: "Safak Kocaoglu",
    status: "active",
  },
];

export const Restaurants = [
  {
    name: "jubran",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "jubran",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "jubran",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "jubran",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "jubran",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "jubran",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "jubran",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "jubran",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "jubran",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "jubran",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
];

export const Hotels = [
  {
    name: "rotana",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "rotana",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "rotana",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "rotana",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "rotana",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "rotana",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "rotana",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "rotana",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "rotana",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "rotana",
    img: "post/1.jpeg",
    description: "Love For All, Hatred For None.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
];
export const activities = [
  {
    name: "petra",
    img: "post/1.jpeg",
    description: "visit petra.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "petra",
    img: "post/1.jpeg",
    description: "visit petra.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "petra",
    img: "post/1.jpeg",
    description: "visit petra.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "petra",
    img: "post/1.jpeg",
    description: "visit petra.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "petra",
    img: "post/1.jpeg",
    description: "visit petra.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "petra",
    img: "post/1.jpeg",
    description: "visit petra.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "petra",
    img: "post/1.jpeg",
    description: "visit petra.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "petra",
    img: "post/1.jpeg",
    description: "visit petra.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "petra",
    img: "post/1.jpeg",
    description: "visit petra.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
  {
    name: "petra",
    img: "post/1.jpeg",
    description: "visit petra.",
    rating: 9,
    location: 32,
    ownerId: 1,
  },
];
